---
openapi: 3.1.0
info:
  title: Search API
  version: latest
paths:
  /:
    post:
      summary: Search
      tags:
      - Search
      operationId: search
      description: Search with Query
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Query'
      responses:
        200:
          description: Success

components:
  schemas:
    Query:
      properties:
        ledgers:
          items:
            type: string
          type: array
        nextToken:
          type: string
        size:
          type: integer
        terms:
          items:
            type: string
          type: array
        target:
          type: string
      type: object
    Response:
      properties:
        data:
          description: The payload
          type: object
        cursor:
          type: object
          properties:
            pageSize:
              type: number
            hasMore:
              type: boolean
            total:
              type: object
              properties:
                value:
                  type: number
                relation:
                  type: string
            next:
              type: string
            previous:
              type: string
            data:
              type: array
              items:
                allOf:
                - type: object
        kind:
          description: The kind of the object, either "TRANSACTION" or "META"
          type: string
        ledger:
          description: The ledger
          type: string
      type: object
