swagger: "2.0"
info:
  title: Search API
  version: latest
definitions:
  Query:
    properties:
      ledgers:
        items:
          type: string
        type: array
      nextToken:
        type: string
      size:
        type: integer
      terms:
        items:
          type: string
        type: array
  Response:
    properties:
      data:
        description: The payload
        type: object
      kind:
        description: The kind of the object, either "TRANSACTION" or "META"
        type: string
      ledger:
        description: The ledger
        type: string
paths:
  /:
    post:
      consumes:
      - application/json
      operationId: search
      parameters:
      - description: the query
        in: body
        name: query
        required: true
        schema:
          "$ref": '#/definitions/Query'
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            "$ref": '#/definitions/Response'
